const defaultCards = [
  { id: 0, display: 1, isPicked: false, isSelected: false },
  { id: 1, display: 2, isPicked: false, isSelected: false },
  { id: 2, display: 3, isPicked: false, isSelected: false },
  { id: 3, display: 4, isPicked: false, isSelected: false },
  { id: 4, display: 5, isPicked: false, isSelected: false },
  { id: 5, display: 6, isPicked: false, isSelected: false },
  { id: 6, display: 7, isPicked: false, isSelected: false },
  { id: 7, display: 8, isPicked: false, isSelected: false },
  { id: 8, display: 9, isPicked: false, isSelected: false },
  { id: 9, display: 10, isPicked: false, isSelected: false },
  { id: 10, display: 11, isPicked: false, isSelected: false },
  { id: 11, display: 12, isPicked: false, isSelected: false },
  { id: 12, display: 13, isPicked: false, isSelected: false },
  { id: 13, display: 14, isPicked: false, isSelected: false },
  { id: 14, display: 15, isPicked: false, isSelected: false },
  { id: 15, display: 16, isPicked: false, isSelected: false },
  { id: 16, display: 17, isPicked: false, isSelected: false },
  { id: 17, display: 18, isPicked: false, isSelected: false },
  { id: 18, display: 19, isPicked: false, isSelected: false },
  { id: 19, display: 20, isPicked: false, isSelected: false },
  { id: 20, display: 21, isPicked: false, isSelected: false },
  { id: 21, display: 22, isPicked: false, isSelected: false },
  { id: 22, display: 23, isPicked: false, isSelected: false },
  { id: 23, display: 24, isPicked: false, isSelected: false },
  { id: 24, display: 25, isPicked: false, isSelected: false },
  { id: 25, display: 26, isPicked: false, isSelected: false },
  { id: 26, display: 27, isPicked: false, isSelected: false },
  { id: 27, display: 28, isPicked: false, isSelected: false },
  { id: 28, display: 29, isPicked: false, isSelected: false },
  { id: 29, display: 30, isPicked: false, isSelected: false },
  { id: 30, display: 31, isPicked: false, isSelected: false },
  { id: 31, display: 32, isPicked: false, isSelected: false },
  { id: 32, display: 33, isPicked: false, isSelected: false },
  { id: 33, display: 34, isPicked: false, isSelected: false },
  { id: 34, display: 35, isPicked: false, isSelected: false },
  { id: 35, display: 36, isPicked: false, isSelected: false },
  { id: 36, display: 37, isPicked: false, isSelected: false },
  { id: 37, display: 38, isPicked: false, isSelected: false },
  { id: 38, display: 39, isPicked: false, isSelected: false },
  { id: 39, display: 40, isPicked: false, isSelected: false },
];

export default defaultCards;
