
    const sharedCopy =
    {
  "en": {
    "CHIP_INFO": "Chip Value",
    "EDGE_NAME": "Edge",
    "PLACEHOLDER_CHAT": "Type your Message",
    "CLEAR_NAME": "Clear",
    "UNDO_NAME": "Undo",
    "EVEN_NAME": "Even",
    "ODD_NAME": "Odd",
    "TO": "to",
    "TOTAL_BET_NAME": "Total bet",
    "BET_NAME": "Bet",
    "DOUBLE_DOWN_NAME": "Double Down",
    "AUTO_BET_NAME": "Start Auto Bet",
    "MANUAL_NAME": "Manual",
    "AUTO_NAME": "Auto",
    "GAMES_NAME": "Games",
    "FOLLOW_US": "Follow us"
  },
  "kr": {
    "CHIP_INFO": "칩 가치",
    "EDGE_NAME": "하우스 엣지",
    "PLACEHOLDER_CHAT": "메시지 입력",
    "CLEAR_NAME": "클리어",
    "UNDO_NAME": "취소",
    "EVEN_NAME": "짝수",
    "ODD_NAME": "홀수",
    "TO": "to",
    "TOTAL_BET_NAME": "총 베트",
    "DOUBLE_DOWN_NAME": "2배 베팅",
    "BET_NAME": "베트",
    "AUTO_BET_NAME": "자동 베트 시작",
    "MANUAL_NAME": "수동",
    "AUTO_NAME": "자동",
    "GAMES_NAME": "Games",
    "FOLLOW_US": "Follow us"
  },
  "ch": {
    "CHIP_INFO": "筹码值",
    "EDGE_NAME": "庄家优势",
    "PLACEHOLDER_CHAT": "输入你的消息",
    "DOUBLE_DOWN_NAME": "加倍下注",
    "CLEAR_NAME": "清空",
    "UNDO_NAME": "取消",
    "EVEN_NAME": "偶数",
    "ODD_NAME": "奇数",
    "TO": "to",
    "TOTAL_BET_NAME": "总投注",
    "BET_NAME": "下注",
    "AUTO_BET_NAME": "开始自动下注",
    "MANUAL_NAME": "手动",
    "AUTO_NAME": "自动",
    "GAMES_NAME": "Games",
    "FOLLOW_US": "Follow us"
  },
  "jp": {
    "CHIP_INFO": "チップバリュー",
    "EDGE_NAME": "エッジ",
    "DOUBLE_DOWN_NAME": "Double Down",
    "PLACEHOLDER_CHAT": "メッセージを入力",
    "CLEAR_NAME": "クリア",
    "UNDO_NAME": "アンドゥ(取消)",
    "EVEN_NAME": "イーブン(偶数)",
    "ODD_NAME": "オッド(奇数）",
    "TO": "to",
    "TOTAL_BET_NAME": "トータルベッド",
    "BET_NAME": "ベット",
    "AUTO_BET_NAME": "オートベット開始",
    "MANUAL_NAME": "マニュアル",
    "AUTO_NAME": "オート",
    "GAMES_NAME": "Games",
    "FOLLOW_US": "Follow us"
  },
  "ru": {
    "CHIP_INFO": "Номинал Фишки",
    "EDGE_NAME": "Edge",
    "PLACEHOLDER_CHAT": "Отправить сообщение",
    "CLEAR_NAME": "Очистить",
    "UNDO_NAME": "Отменить",
    "EVEN_NAME": "Чет",
    "ODD_NAME": "Нечет",
    "TO": "до",
    "TOTAL_BET_NAME": "Всего Ставок",
    "BET_NAME": "Ставка",
    "DOUBLE_DOWN_NAME": "Удвоить Ставку",
    "AUTO_BET_NAME": "Start Auto Bet",
    "MANUAL_NAME": "Вручную",
    "AUTO_NAME": "Авто",
    "GAMES_NAME": "Игры",
    "FOLLOW_US": "Соцсети"
  }
}
    export default sharedCopy;
    